- hosts: localhost
  remote_user: root

  vars_prompt:
     
    - name: "user_name"
      prompt: "Enter username"
      private: no

    - name: "user_password"
      prompt: "Enter a password for the new user"
      private: yes
      encrypt: "sha512_crypt"
      salt_size: 7    

  tasks: 

    - name: Checking for wheel group
      group: 
        name: wheel
        state: present

    - name: Create the non-root user
      user: name= "{{user_name}}" comment="{{description}}" password= "{{user_password}}" home="{{home_dir}}" shell= "/bin/bash"
