---
# tasks file for nginx

- name: Install nginx web server
  yum: name=nginx state=installed
  notify:
    - start nginx

- name: Upload default index.nginxinst for host
  copy: src=index.nginxinst dest=/usr/share/nginx/www/ mode=0644
  register: nginxindex
  ignore_errors: true

- name: Remove index.html for host
  command: rm /usr/share/nginx/wwwindex.html
  when: nginxindex|success

- name: Upload default index.html for host
  copy: src=index.html dest=/usr/share/nginx/www/ mode=0644
  when: nginxindex|failed
  notify:
    - restart nginx

